/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicResumeRouteImport } from './routes/api/public/resume'
import { Route as ApiPublicQuestionsRouteImport } from './routes/api/public/questions'
import { Route as ApiPublicPlanRouteImport } from './routes/api/public/plan'
import { Route as ApiPublicInterviewRouteImport } from './routes/api/public/interview'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResumeRoute = ApiPublicResumeRouteImport.update({
  id: '/api/public/resume',
  path: '/api/public/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuestionsRoute = ApiPublicQuestionsRouteImport.update({
  id: '/api/public/questions',
  path: '/api/public/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlanRoute = ApiPublicPlanRouteImport.update({
  id: '/api/public/plan',
  path: '/api/public/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInterviewRoute = ApiPublicInterviewRouteImport.update({
  id: '/api/public/interview',
  path: '/api/public/interview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/interview': typeof ApiPublicInterviewRoute
  '/api/public/plan': typeof ApiPublicPlanRoute
  '/api/public/questions': typeof ApiPublicQuestionsRoute
  '/api/public/resume': typeof ApiPublicResumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/interview': typeof ApiPublicInterviewRoute
  '/api/public/plan': typeof ApiPublicPlanRoute
  '/api/public/questions': typeof ApiPublicQuestionsRoute
  '/api/public/resume': typeof ApiPublicResumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/interview': typeof ApiPublicInterviewRoute
  '/api/public/plan': typeof ApiPublicPlanRoute
  '/api/public/questions': typeof ApiPublicQuestionsRoute
  '/api/public/resume': typeof ApiPublicResumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/public/interview'
    | '/api/public/plan'
    | '/api/public/questions'
    | '/api/public/resume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/public/interview'
    | '/api/public/plan'
    | '/api/public/questions'
    | '/api/public/resume'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/public/interview'
    | '/api/public/plan'
    | '/api/public/questions'
    | '/api/public/resume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicInterviewRoute: typeof ApiPublicInterviewRoute
  ApiPublicPlanRoute: typeof ApiPublicPlanRoute
  ApiPublicQuestionsRoute: typeof ApiPublicQuestionsRoute
  ApiPublicResumeRoute: typeof ApiPublicResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resume': {
      id: '/api/public/resume'
      path: '/api/public/resume'
      fullPath: '/api/public/resume'
      preLoaderRoute: typeof ApiPublicResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/questions': {
      id: '/api/public/questions'
      path: '/api/public/questions'
      fullPath: '/api/public/questions'
      preLoaderRoute: typeof ApiPublicQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plan': {
      id: '/api/public/plan'
      path: '/api/public/plan'
      fullPath: '/api/public/plan'
      preLoaderRoute: typeof ApiPublicPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/interview': {
      id: '/api/public/interview'
      path: '/api/public/interview'
      fullPath: '/api/public/interview'
      preLoaderRoute: typeof ApiPublicInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicInterviewRoute: ApiPublicInterviewRoute,
  ApiPublicPlanRoute: ApiPublicPlanRoute,
  ApiPublicQuestionsRoute: ApiPublicQuestionsRoute,
  ApiPublicResumeRoute: ApiPublicResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
